### ISSUE TITLE
Getting out of scope domains output

### ISSUE THREAD

**Issue by fail-open** [projectdiscovery/urlfinder#18]
**Describe the bug**
I am still digging to see how consistent this is, but I am doing basic urlfinder scans with jsonl output. When I extract the url field and look at my unique values, I am getting results that were not what I input. 
**urlfinder version**
Include the version of urlfinder you are using, `urlfinder -version`

**Complete command you used to reproduce this**
urlfinder -list target.txt -output output.txt
 jq -r '.url' output | unfurl -u domain

```
small sampling of output 
jokadola.blogspot.com
www.robloxfreerobux.biz
trchatsohbetsitesi.blogspot.com
redneckpassions.com
rogabubu.blogspot.com
rinukeyo.blogspot.com
johoteke.blogspot.com
nickelbackpassions.com
ricezeyi.blogspot.com
www.italia-risparmio.it
happyland.net.vn
https
rofoheqo.blogspot.com
jogeguta.blogspot.com
qm5t0kieiv.ga
hubcontrol.ga
eusouafrpromotora.blogspot.com
cilveli.net
market.android.com
bola81.online
tvpassions.com
allrevolution.ga
www.tusaybat.com
tcchatrandom.blogspot.com
```

target.txt contains just google.com

**Comment by fail-open** [comment]
Not sure if related or should be its own bug, but I did a run with a target file containing 3 domains. I passed that in to both -list and -match hoping it would restrict it to the domains that way, but I still got some external domains popping up.

**Comment by mhmdiaa** [comment]
This seems to be caused by the [regex extractor](https://github.com/projectdiscovery/urlfinder/blob/dev/pkg/extractor/regex_extractor.go) used [here](https://github.com/projectdiscovery/urlfinder/blob/dev/pkg/source/waybackarchive/waybackarchive.go#L50) and [here](https://github.com/projectdiscovery/urlfinder/blob/dev/pkg/source/commoncrawl/commoncrawl.go#L141).

The extractor tries to extract every URL found in the results (that are URLs themselves), so if it encounters `https://foo.com/redirect?url=https://bar.com`, the regex will extract `https://bar.com` and add it to the results as well.
